-- Traductions d'affichage des notices. La notice source reste toujours intacte :
-- chaque ligne est une version cachee pour une langue cible precise.
CREATE TABLE IF NOT EXISTS traductions_publications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    langue_cible VARCHAR(5) NOT NULL,
    empreinte_source VARCHAR(64) NOT NULL,
    titre VARCHAR(500),
    resume TEXT,
    mots_cles TEXT,
    modele VARCHAR(100),
    date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_traductions_publications_document_langue UNIQUE (document_id, langue_cible)
);
