CREATE TABLE institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    domaine_email VARCHAR(255),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    solde_credits INTEGER NOT NULL DEFAULT 0 CHECK (solde_credits >= 0),
    credits_bienvenue_accordes BOOLEAN NOT NULL DEFAULT FALSE,
    achats_suspendus BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_institutions_domaine_email UNIQUE (domaine_email)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prenom VARCHAR(100),
    nom VARCHAR(100),
    email VARCHAR(255) NOT NULL,
    mot_de_passe_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE langues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(5) NOT NULL,
    libelle VARCHAR(50) NOT NULL,
    CONSTRAINT uk_langues_code UNIQUE (code)
);

CREATE TABLE types_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    libelle VARCHAR(100) NOT NULL,
    CONSTRAINT uk_types_documents_code UNIQUE (code)
);

CREATE TABLE auteurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_complet VARCHAR(255) NOT NULL,
    orcid VARCHAR(19)
);

CREATE TABLE mots_cles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(150) NOT NULL,
    CONSTRAINT uk_mots_cles_libelle UNIQUE (libelle)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_fichier VARCHAR(255) NOT NULL,
    chemin_fichier VARCHAR(500),
    image_couverture VARCHAR(500),
    taille_fichier BIGINT,
    type_mime VARCHAR(100),
    texte_extrait TEXT,
    statut VARCHAR(20) NOT NULL,
    visibilite VARCHAR(20) NOT NULL,
    search_vector TEXT,
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    importe_par BIGINT REFERENCES users(id)
);

CREATE TABLE metadonnees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    titre VARCHAR(500),
    resume TEXT,
    date_publication DATE,
    classification VARCHAR(255),
    langue_id BIGINT REFERENCES langues(id),
    type_document_id BIGINT REFERENCES types_documents(id),
    statut VARCHAR(20) NOT NULL,
    date_validation TIMESTAMP,
    validee_par BIGINT REFERENCES users(id),
    date_generation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_metadonnees_document UNIQUE (document_id)
);

CREATE TABLE documents_auteurs (
    document_id BIGINT NOT NULL REFERENCES documents(id),
    auteur_id BIGINT NOT NULL REFERENCES auteurs(id),
    ordre_auteur INTEGER,
    PRIMARY KEY (document_id, auteur_id)
);

CREATE TABLE documents_mots_cles (
    document_id BIGINT NOT NULL REFERENCES documents(id),
    mot_cle_id BIGINT NOT NULL REFERENCES mots_cles(id),
    PRIMARY KEY (document_id, mot_cle_id)
);

CREATE TABLE enrichissements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    lance_par BIGINT REFERENCES users(id),
    statut VARCHAR(20) NOT NULL,
    modele_llm VARCHAR(100),
    version_prompt VARCHAR(50),
    reponse_brute TEXT,
    message_erreur TEXT,
    date_debut TIMESTAMP,
    date_fin TIMESTAMP
);

CREATE TABLE suggestions_metadonnees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrichissement_id BIGINT NOT NULL REFERENCES enrichissements(id),
    champ VARCHAR(50) NOT NULL,
    valeur_suggeree TEXT,
    score_confiance NUMERIC(3,2),
    decision VARCHAR(20),
    valeur_finale TEXT
);

CREATE TABLE logs_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    action VARCHAR(50),
    type_entite VARCHAR(50),
    entite_id BIGINT,
    details TEXT,
    adresse_ip VARCHAR(45),
    date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE configurations (
    cle VARCHAR(100) PRIMARY KEY,
    valeur TEXT,
    modifie_par BIGINT REFERENCES users(id),
    date_modification TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE packs_credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    quantite INTEGER NOT NULL,
    montant_paye NUMERIC(10,2),
    reference_paiement VARCHAR(255),
    statut VARCHAR(20) NOT NULL,
    date_achat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mouvements_credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    type VARCHAR(30) NOT NULL,
    quantite INTEGER NOT NULL,
    solde_apres INTEGER NOT NULL,
    description VARCHAR(255),
    enrichissement_id BIGINT REFERENCES enrichissements(id),
    date_mouvement TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    CONSTRAINT uk_password_reset_tokens_hash UNIQUE (token_hash)
);

CREATE TABLE consentements_paiement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    type VARCHAR(40) NOT NULL,
    version_document VARCHAR(40) NOT NULL,
    accepte_at TIMESTAMP NOT NULL,
    ip VARCHAR(64) NOT NULL
);

CREATE TABLE evenements_stripe_traites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    type_evenement VARCHAR(100) NOT NULL,
    traite_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_evenements_stripe_event_id UNIQUE (event_id)
);

CREATE INDEX idx_documents_institution_id ON documents(institution_id);
CREATE INDEX idx_documents_statut_visibilite ON documents(statut, visibilite);
CREATE INDEX idx_enrichissements_document_id ON enrichissements(document_id);
CREATE INDEX idx_suggestions_enrichissement_id ON suggestions_metadonnees(enrichissement_id);
CREATE INDEX idx_logs_audit_user_id ON logs_audit(user_id);
CREATE INDEX idx_logs_audit_date_creation ON logs_audit(date_creation);
CREATE INDEX idx_packs_credits_institution_id ON packs_credits(institution_id);
CREATE INDEX idx_mouvements_credits_institution_date ON mouvements_credits(institution_id, date_mouvement);
