-- Idempotent : une base historique peut deja contenir cette table,
-- creee par Hibernate avant la mise en place de Flyway.
CREATE TABLE IF NOT EXISTS taches_extraction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    enrichissement_id BIGINT REFERENCES enrichissements(id),
    institution_id BIGINT NOT NULL REFERENCES institutions(id),
    lot_id VARCHAR(36) NOT NULL,
    statut VARCHAR(20) NOT NULL,
    priorite INTEGER NOT NULL DEFAULT 0,
    tentatives INTEGER NOT NULL DEFAULT 0,
    prochaine_tentative_at TIMESTAMP,
    verrouille_par VARCHAR(100),
    verrouille_at TIMESTAMP,
    cree_par BIGINT REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_taches_extraction_statut_prochaine_tentative
    ON taches_extraction(statut, prochaine_tentative_at);
CREATE INDEX IF NOT EXISTS idx_taches_extraction_lot_id ON taches_extraction(lot_id);
